@Library('my_ocp_sharelib') _  
import com.aviro.OpenShiftHelper  

pipeline {
    //agent any  
    agent {
        label 'builder4'
    }

    environment {
        OC_TOKEN = credentials('kingopenshift-id')  // Jenkins credentials
        OC_SERVER = "https://api.rm1.0a51.p1.openshiftapps.com:6443"
        PROJECT = "kekuda-king-dev"
        IMAGE = "molacon/paas:latest"
        APP_NAME = "web-terminal-tooling"
        APP_DEPLOYMENT = "workspace62e89aa8716c4c83"
    }

    stages {
        stage('Login to OpenShift') {
            steps {
                script {
                    OpenShiftHelper.login(this, OC_TOKEN, OC_SERVER)
                }
            }
        }

        // stage('Deploy Application') {
        //     steps {
        //         script {
        //             OpenShiftHelper.deploy(this, PROJECT, IMAGE, APP_NAME)
        //         }
        //     }
        // }
        stage('Trivy Security Scan') {
 
                                        steps {
 
                                            sh '''
                                            sudo docker run --rm \
                                            -v /var/run/docker.sock:/var/run/docker.sock \
                                            -v $PWD:/root/reports \
                                            aquasec/trivy image \
                                            --format template \
                                            --template "@/contrib/html.tpl" \
                                            -o /root/reports/trivy-report.html \
                                            ${IMAGE_NAME}:${IMAGE_TAG}
                                            '''
 
                                        }
 
                                    }
                                    stage('Publish Trivy Report') {
 
                                        steps {
 
                                            publishHTML(target: [
                                            allowMissing: true,
                                            alwaysLinkToLastBuild: false,
                                            keepAll: true,
                                            reportDir: '.',
                                            reportFiles: 'trivy-report.html',
                                            reportName: 'Trivy Security Report',
                                            alwaysLinkToLastBuild: true
                                            ])
 
                                        }
 
                                    }

        stage('Deploy Application') {
            steps {
                script {
                    OpenShiftHelper.deployDeployment(this, PROJECT, IMAGE, APP_NAME, APP_DEPLOYMENT)
                }
            }
        }

        stage('Check Deployment Status') {
            steps {
                script {
                    if (!OpenShiftHelper.checkDeployment(this, PROJECT, APP_NAME, APP_DEPLOYMENT)) {
                        error "Le déploiement a échoué !"
                    } else {
                        echo "L'application a été déployée avec succès sur OpenShift !"
                    }
                }
            }
        }
    }
}
